project_name: upstash-redis-local
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
brews:
  -
    tap:
      owner: DarthBenro008
      name: homebrew-upstash-redis-local
    description: "upstash-redis-local - Test @upstash/redis locally!"
    folder: Formula
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}"
release:
  header: |
  ## Upstash-redis-local Release ({{ .Date }})
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"